services:
  - type: web
    name: kahoot-spammer
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python ic3_kahoot_full.py 9595700 30 IC3 0.5 --headless --auto_answer"
    routes:
      - type: http
        path: /
